# Generated by Django 3.2.4 on 2021-07-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=300, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='LinkedInd'),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='portfolio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Portafolio'),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='repo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Repositorio'),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='twitter',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='valoration',
            field=models.IntegerField(blank=True, null=True, verbose_name='valoración'),
        ),
    ]
