# Generated by Django 3.2.4 on 2021-07-07 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=300, null=True, verbose_name='Email')),
                ('repo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Repositorio')),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True, verbose_name='LinkedInd')),
                ('twitter', models.CharField(blank=True, max_length=500, null=True, verbose_name='Twitter')),
                ('instagram', models.CharField(blank=True, max_length=500, null=True, verbose_name='Instagram')),
                ('portfolio', models.CharField(blank=True, max_length=500, null=True, verbose_name='Portafolio')),
                ('valoration', models.IntegerField(blank=True, null=True, verbose_name='valoración')),
            ],
            options={
                'verbose_name': 'DetailsModel',
                'verbose_name_plural': 'DetailsModels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('photo', models.ImageField(blank=True, default='img/user.jpg', null=True, upload_to='user/%Y/%m/%d', verbose_name='Foto')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.detailsmodel')),
            ],
            options={
                'verbose_name': 'UserModel',
                'verbose_name_plural': 'UserModels',
                'ordering': ['id'],
            },
        ),
    ]
